---
title: "Table of Pre-requisites"
author: "Irene Spada"
date: "2023-08-08"
output: html_document
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
# Data set up

# Load libraries 
library(tidyverse)
library(DT) 

# Load data
pairs_probs_and_relevance <- read.csv("data/pairs_probs_and_relevance.csv")

# Set columns' names 
i1 <- pairs_probs_and_relevance %>%
  arrange(desc(start_skill_relevance)) %>% 
  select("From Competence" = from_skill, 
         "To Competence" = to_skill,
         "Link Probability" = link_probability, 
         "Relevance (From)" = start_skill_relevance, 
         "Relevance (To)" = end_skill_relevance, 
         "Type (From)" = skillType_from, 
         "Type (To)" = skillType_to,
         "Reuse Level (From)" = reuseLevel_from,
         "Reuse Level (To)" = reuseLevel_to) 
```

The table shows the pre-requisite relations among the competences related to the Project Management field. 

```{r echo=FALSE, message=FALSE, warning=FALSE}
# Table Displays

DT::datatable(i1, filter = "top", rownames = F, class = "cell-border stripe",
              extensions = 'Buttons', options = list(
                dom = 'Bfrtip', 
                buttons = c('copy', 'csv', 'excel', 'pdf', 'print'))
              )
```
